version: '3.8'

services:
  spark-master:
    build: .
    container_name: spark-master
    hostname: master
    environment:
      - SPARK_MASTER_HOST=master
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/logs
      - SPARK_EVENTLOG_ENABLED=true
      - SPARK_EVENTLOG_DIR=/opt/spark/logs
    command: ["sh", "/opt/spark/start_services.sh"]
    ports:
      - "4040:4040"   # Spark Master Web UI port
      - "7077:8080"   # Spark Master port
      - "8888:8888"   # Jupyter 
    volumes:
      - ./data:/data
      - spark-logs:/opt/spark/logs
    networks:
      - spark-network

  spark-worker-1:
    image: docker.io/apache/spark:3.5.2-scala2.12-java11-python3-r-ubuntu
    container_name: spark-worker-1
    hostname: worker-1
    user: root
    environment:
      - SPARK_MASTER_URL=spark://master:7077
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://master:7077"]
    ports:
      - "8081:8081"   # Spark Worker Web UI port
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-worker-2:
    image: docker.io/apache/spark:3.5.2-scala2.12-java11-python3-r-ubuntu
    container_name: spark-worker-2
    hostname: worker-2
    user: root
    environment:
      - SPARK_MASTER_URL=spark://master:7077
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://master:7077"]
    ports:
      - "8082:8081"   # Spark Worker Web UI port (different port to avoid conflict)
    volumes:
      - ./data:/data
    depends_on:
      - spark-master
    networks:
      - spark-network

  spark-history-server:
    image: docker.io/apache/spark:3.5.2-scala2.12-java11-python3-r-ubuntu
    container_name: spark-history-server
    hostname: history-server
    user: root
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/logs
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.history.HistoryServer"]
    ports:
      - "18080:18080" # Spark History Server Web UI port
    volumes:
      - spark-logs:/opt/spark/logs
    depends_on:
      - spark-master
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge

volumes:
  spark-logs: